#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIRECTORY="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly PROJECT_DIRECTORY
readonly BUILD_SCRIPT="${PROJECT_DIRECTORY}/scripts/build-watchdog.sh"
TEST_DIRECTORY="$(mktemp -d)"

cleanup() {
    rm -rf -- "$TEST_DIRECTORY"
}
trap cleanup EXIT

for command_name in bash cmp grep mktemp; do
    command -v "$command_name" >/dev/null 2>&1 || {
        printf 'Missing test dependency: %s\n' "$command_name" >&2
        exit 2
    }
done

bash "$BUILD_SCRIPT" --check >"${TEST_DIRECTORY}/check.out"
grep -Fx 'Generated service-watchdog.sh is current.' "${TEST_DIRECTORY}/check.out" >/dev/null

generated_file="${TEST_DIRECTORY}/service-watchdog.sh"
printf 'stale\n' >"$generated_file"
set +e
bash "$BUILD_SCRIPT" --check --output "$generated_file" >"${TEST_DIRECTORY}/stale.out" 2>&1
stale_status=$?
set -e
[[ "$stale_status" == 1 ]]
grep -F 'Generated service-watchdog.sh is stale; run scripts/build-watchdog.sh.' "${TEST_DIRECTORY}/stale.out" >/dev/null

bash "$BUILD_SCRIPT" --output "$generated_file" >"${TEST_DIRECTORY}/build.out"
cmp --silent "$generated_file" "${PROJECT_DIRECTORY}/service-watchdog.sh"
grep -Fx '# Generated by scripts/build-watchdog.sh from lib/watchdog/. DO NOT EDIT.' "$generated_file" >/dev/null

set +e
bash "$BUILD_SCRIPT" --unknown >"${TEST_DIRECTORY}/invalid.out" 2>&1
invalid_status=$?
set -e
[[ "$invalid_status" == 2 ]]
grep -F 'Unknown option: --unknown' "${TEST_DIRECTORY}/invalid.out" >/dev/null

printf 'Single-file build test passed.\n'
