#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIRECTORY="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly PROJECT_DIRECTORY
readonly MODULE_DIRECTORY="${PROJECT_DIRECTORY}/lib/watchdog"
readonly DEFAULT_OUTPUT="${PROJECT_DIRECTORY}/service-watchdog.sh"
readonly MODULES=(
    00-bootstrap.sh
    10-configuration.sh
    20-notifications.sh
    30-checks.sh
    40-state-federation.sh
    50-lifecycle.sh
    60-history-status.sh
    90-main.sh
)

usage() {
    cat <<'EOF'
Usage: scripts/build-watchdog.sh [--check] [--output FILE]

Builds the single-file service-watchdog.sh distribution from lib/watchdog/.
  --check          Fail when the tracked distribution is stale.
  --output FILE    Write the generated distribution to FILE.
EOF
}

render_distribution() {
    local destination="$1" module

    {
        printf '#!/usr/bin/env bash\n'
        printf '# Generated by scripts/build-watchdog.sh from lib/watchdog/. DO NOT EDIT.\n'
        for module in "${MODULES[@]}"; do
            [[ -r "${MODULE_DIRECTORY}/${module}" ]] || {
                printf 'Missing watchdog source module: %s\n' "${MODULE_DIRECTORY}/${module}" >&2
                return 1
            }
            cat "${MODULE_DIRECTORY}/${module}"
        done
    } >"$destination"
}

check_only=0
output_file="$DEFAULT_OUTPUT"
while (( $# > 0 )); do
    case "$1" in
        --check) check_only=1; shift ;;
        --output)
            (( $# >= 2 )) || { printf '%s\n' '--output requires a file path.' >&2; exit 2; }
            output_file="$2"
            shift 2
            ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done

if (( check_only == 1 )); then
    temporary_file="$(mktemp "${TMPDIR:-/tmp}/service-watchdog.build.XXXXXX")"
    trap 'rm -f -- "$temporary_file"' EXIT
    render_distribution "$temporary_file"
    if ! cmp --silent "$temporary_file" "$output_file"; then
        printf 'Generated %s is stale; run scripts/build-watchdog.sh.\n' "${output_file##*/}" >&2
        exit 1
    fi
    printf 'Generated %s is current.\n' "${output_file##*/}"
    exit 0
fi

output_directory="$(dirname -- "$output_file")"
[[ -d "$output_directory" && -w "$output_directory" ]] || {
    printf 'Output directory is not writable: %s\n' "$output_directory" >&2
    exit 2
}
temporary_file="$(mktemp "${output_directory}/.service-watchdog.build.XXXXXX")"
trap 'rm -f -- "$temporary_file"' EXIT
render_distribution "$temporary_file"
chmod 0755 "$temporary_file"
mv -f -- "$temporary_file" "$output_file"
trap - EXIT
printf 'Generated %s\n' "$output_file"
